/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { ContactWhereUniqueInput } from "../../contact/base/ContactWhereUniqueInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { EnumNewsItemStatus } from "./EnumNewsItemStatus";
import { EnumNewsItemTags } from "./EnumNewsItemTags";
@InputType()
class NewsItemWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  body?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ContactWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ContactWhereUniqueInput)
  @IsOptional()
  @Field(() => ContactWhereUniqueInput, {
    nullable: true,
  })
  contacts?: ContactWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  createdBy?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  slug?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumNewsItemStatus,
  })
  @IsEnum(EnumNewsItemStatus)
  @IsOptional()
  @Field(() => EnumNewsItemStatus, {
    nullable: true,
  })
  status?: "Published" | "Draft" | "Expired";

  @ApiProperty({
    required: false,
    enum: EnumNewsItemTags,
  })
  @IsEnum(EnumNewsItemTags)
  @IsOptional()
  @Field(() => EnumNewsItemTags, {
    nullable: true,
  })
  tags?:
    | "Politiek"
    | "Misdaad"
    | "Finansies"
    | "Hofsake"
    | "Omgewing"
    | "Vermaak"
    | "Sport"
    | "Ongelukke"
    | "Dagboek"
    | "Internasionaal"
    | "Tegnologie"
    | "Gesondheid"
    | "Arbeid"
    | "Plaaslik";
}
export { NewsItemWhereInput };
