/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsDate,
  IsEnum,
} from "class-validator";
import { Contact } from "../../contact/base/Contact";
import { Type } from "class-transformer";
import { User } from "../../user/base/User";
import { EnumNewsItemStatus } from "./EnumNewsItemStatus";
import { EnumNewsItemTags } from "./EnumNewsItemTags";
@ObjectType()
class NewsItem {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  body!: string | null;

  @ApiProperty({
    required: false,
    type: () => Contact,
  })
  @ValidateNested()
  @Type(() => Contact)
  @IsOptional()
  contacts?: Contact | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  createdBy?: User | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  slug!: string;

  @ApiProperty({
    required: false,
    enum: EnumNewsItemStatus,
  })
  @IsEnum(EnumNewsItemStatus)
  @IsOptional()
  @Field(() => EnumNewsItemStatus, {
    nullable: true,
  })
  status?: "Published" | "Draft" | "Expired" | null;

  @ApiProperty({
    required: false,
    enum: EnumNewsItemTags,
  })
  @IsEnum(EnumNewsItemTags)
  @IsOptional()
  @Field(() => EnumNewsItemTags, {
    nullable: true,
  })
  tags?:
    | "Politiek"
    | "Misdaad"
    | "Finansies"
    | "Hofsake"
    | "Omgewing"
    | "Vermaak"
    | "Sport"
    | "Ongelukke"
    | "Dagboek"
    | "Internasionaal"
    | "Tegnologie"
    | "Gesondheid"
    | "Arbeid"
    | "Plaaslik"
    | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { NewsItem };
