/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ContactService } from "../contact.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ContactCreateInput } from "./ContactCreateInput";
import { ContactWhereInput } from "./ContactWhereInput";
import { ContactWhereUniqueInput } from "./ContactWhereUniqueInput";
import { ContactFindManyArgs } from "./ContactFindManyArgs";
import { ContactUpdateInput } from "./ContactUpdateInput";
import { Contact } from "./Contact";
import { NewsItemFindManyArgs } from "../../newsItem/base/NewsItemFindManyArgs";
import { NewsItem } from "../../newsItem/base/NewsItem";
import { NewsItemWhereUniqueInput } from "../../newsItem/base/NewsItemWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ContactControllerBase {
  constructor(
    protected readonly service: ContactService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Contact",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Contact })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: ContactCreateInput): Promise<Contact> {
    return await this.service.create({
      data: data,
      select: {
        cellphoneNumber: true,
        company: true,
        createdAt: true,
        id: true,
        name: true,
        surname: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Contact",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Contact] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ContactFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Contact[]> {
    const args = plainToClass(ContactFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        cellphoneNumber: true,
        company: true,
        createdAt: true,
        id: true,
        name: true,
        surname: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Contact",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Contact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ContactWhereUniqueInput
  ): Promise<Contact | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        cellphoneNumber: true,
        company: true,
        createdAt: true,
        id: true,
        name: true,
        surname: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Contact",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Contact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ContactWhereUniqueInput,
    @common.Body() data: ContactUpdateInput
  ): Promise<Contact | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          cellphoneNumber: true,
          company: true,
          createdAt: true,
          id: true,
          name: true,
          surname: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Contact",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Contact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ContactWhereUniqueInput
  ): Promise<Contact | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          cellphoneNumber: true,
          company: true,
          createdAt: true,
          id: true,
          name: true,
          surname: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "NewsItem",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/lastUsed")
  @ApiNestedQuery(NewsItemFindManyArgs)
  async findManyLastUsed(
    @common.Req() request: Request,
    @common.Param() params: ContactWhereUniqueInput
  ): Promise<NewsItem[]> {
    const query = plainToClass(NewsItemFindManyArgs, request.query);
    const results = await this.service.findLastUsed(params.id, {
      ...query,
      select: {
        body: true,

        contacts: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        id: true,
        slug: true,
        status: true,
        tags: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Contact",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/lastUsed")
  async connectLastUsed(
    @common.Param() params: ContactWhereUniqueInput,
    @common.Body() body: NewsItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lastUsed: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Contact",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/lastUsed")
  async updateLastUsed(
    @common.Param() params: ContactWhereUniqueInput,
    @common.Body() body: NewsItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lastUsed: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Contact",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/lastUsed")
  async disconnectLastUsed(
    @common.Param() params: ContactWhereUniqueInput,
    @common.Body() body: NewsItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lastUsed: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
